sonar.organization=hypnozer
sonar.projectKey=hypnozer_python-project-387
sonar.projectName=python-project-387

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/e2e
sonar.exclusions=frontend/src/api/schema.d.ts
sonar.coverage.exclusions=frontend/src/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
