/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Book an advertised free slot as a guest
         * @description The start must exactly match a slot currently offered for the chosen event type. The server derives endsAt, validates the rolling window, and checks interval overlap atomically. A conflict exists when newStart < existingEnd and existingStart < newEnd, across all event types.
         */
        post: operations["BookingOperations_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List event types for the public booking page
         * @description Returns all event types ordered by title ascending. An empty result is returned as [].
         */
        get: operations["EventTypeOperations_listEventTypes"];
        put?: never;
        /** Create an event type as the calendar owner */
        post: operations["EventTypeOperations_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one event type for the public booking page */
        get: operations["EventTypeOperations_getEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List free slots for an event type in the rolling 14-day window
         * @description Returns only slots that fit fully inside predefined owner availability, start in the future, and do not overlap any booking regardless of event type. Slots are ordered by startsAt ascending. Adjacent meetings are allowed. An empty result is returned as slots: [].
         */
        get: operations["EventTypeOperations_listAvailableSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the predefined owner profile */
        get: operations["OwnerOperations_getOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all upcoming bookings across every event type
         * @description Returns bookings whose startsAt is in the future, ordered by startsAt ascending. An empty result is returned as [].
         */
        get: operations["OwnerBookingOperations_listUpcomingBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Machine-readable API error with a human-readable explanation. */
        ApiError: {
            code: components["schemas"]["ErrorCode"];
            message: string;
        };
        /** @description A local-time interval in the owner's predefined weekly schedule. startsAt must be earlier than endsAt. */
        AvailabilityInterval: {
            /** Format: time */
            startsAt: string;
            /** Format: time */
            endsAt: string;
        };
        /** @description A confirmed meeting. endsAt is derived from the event type duration by the server. */
        Booking: {
            id: components["schemas"]["ResourceId"];
            eventTypeId: components["schemas"]["EventTypeId"];
            eventTypeTitle: string;
            /** Format: int32 */
            durationMinutes: number;
            guest: components["schemas"]["Guest"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Guest request for a currently advertised slot. The server derives the end time and atomically rechecks availability. */
        CreateBookingRequest: {
            eventTypeId: components["schemas"]["EventTypeId"];
            /** Format: date-time */
            startsAt: string;
            guest: components["schemas"]["Guest"];
        };
        /** @description Payload used by the owner to create an event type. */
        CreateEventTypeRequest: {
            id: components["schemas"]["EventTypeId"];
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @enum {string} */
        DayOfWeek: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
        /** @enum {string} */
        ErrorCode: "INVALID_REQUEST" | "EVENT_TYPE_NOT_FOUND" | "EVENT_TYPE_ID_EXISTS" | "SLOT_OUTSIDE_BOOKING_WINDOW" | "SLOT_NOT_OFFERED" | "SLOT_UNAVAILABLE" | "INTERNAL_ERROR";
        /** @description A kind of meeting guests can book. */
        EventType: {
            id: components["schemas"]["EventTypeId"];
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Stable identifier supplied by the owner. It is a lowercase URL-safe slug. */
        EventTypeId: string;
        /** @description Contact data supplied by a guest without creating an account. */
        Guest: {
            name: string;
            /** Format: email */
            email: string;
        };
        /** @description An IANA time-zone identifier such as Europe/Moscow. */
        IanaTimeZone: string;
        /** @description The application's single predefined calendar owner. */
        Owner: {
            id: components["schemas"]["ResourceId"];
            name: string;
            timeZone: components["schemas"]["IanaTimeZone"];
            weeklyAvailability: components["schemas"]["WeeklyAvailability"][];
        };
        /**
         * Format: uuid
         * @description Opaque server-generated identifier.
         */
        ResourceId: string;
        /** @description A currently free interval computed for one event type. Timestamps include a UTC offset. */
        Slot: {
            eventTypeId: components["schemas"]["EventTypeId"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        /** @description A rolling 14-calendar-date availability window in the owner's time zone. startsOn is today and endsOn is the thirteenth following date. */
        SlotWindow: {
            /** Format: date */
            startsOn: string;
            /** Format: date */
            endsOn: string;
            ownerTimeZone: components["schemas"]["IanaTimeZone"];
            slots: components["schemas"]["Slot"][];
        };
        /** @description Predefined working intervals for one weekday. Intervals for the same day do not overlap. */
        WeeklyAvailability: {
            dayOfWeek: components["schemas"]["DayOfWeek"];
            intervals: components["schemas"]["AvailabilityInterval"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    BookingOperations_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypeOperations_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypeOperations_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypeOperations_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypeOperations_listAvailableSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotWindow"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    OwnerOperations_getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    OwnerBookingOperations_listUpcomingBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
